### ISSUE TITLE
[REVIEW]: Tracking.jl: Accelerating multi-antenna GNSS receivers with CUDA

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#128]
**Submitting author:** @ozmaden (<a href="http://orcid.org/0000-0003-0614-3988">Can Özmaden</a>)
**Repository:** <a href="https://github.com/ozmaden/GPUAcceleratedTracking" target ="_blank">https://github.com/ozmaden/GPUAcceleratedTracking</a>
**Version:** 
**Editor:** @fcdimitr
**Reviewer:** @lucaferranti, @maleadt
**Archive:** Pending

## Status

[![status](https://proceedings.juliacon.org/papers/f7e56fca6680deb1dc9c3eeb513aa431/status.svg)](https://proceedings.juliacon.org/papers/f7e56fca6680deb1dc9c3eeb513aa431)

Status badge code:

```
HTML: <a href="https://proceedings.juliacon.org/papers/f7e56fca6680deb1dc9c3eeb513aa431"><img src="https://proceedings.juliacon.org/papers/f7e56fca6680deb1dc9c3eeb513aa431/status.svg"></a>
Markdown: [![status](https://proceedings.juliacon.org/papers/f7e56fca6680deb1dc9c3eeb513aa431/status.svg)](https://proceedings.juliacon.org/papers/f7e56fca6680deb1dc9c3eeb513aa431)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ozmaden/GPUAcceleratedTracking" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@lucaferranti & @maleadt, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @vchuravy know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JuliaCon conflict of interest policy](https://proceedings.juliacon.org/guide/authors#coi) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JuliaCon code of conduct](https://proceedings.juliacon.org/coc).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ozmaden/GPUAcceleratedTracking">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Authorship:** Has the submitting author (@ozmaden) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Paper format

- [ ] **Authors:** Does the `paper.tex` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?
- [ ] **Page limit:** Is the page limit for full papers respected by the submitted document?

### Content

- [ ] **Context:** is the scientific context motivating the work correctly presented?
- [ ] **Methodology:** is the approach taken in the work justified, presented with enough details and reference to reproduce it?
- [ ] **Results:** are the results presented and compared to approaches with similar goals?
### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JuliaCon conflict of interest policy](https://proceedings.juliacon.org/guide/authors#coi) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JuliaCon code of conduct](https://proceedings.juliacon.org/coc).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ozmaden/GPUAcceleratedTracking">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Authorship:** Has the submitting author (@ozmaden) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Paper format

- [x] **Authors:** Does the `paper.tex` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?
- [x] **Page limit:** Is the page limit for full papers respected by the submitted document?

### Content

- [x] **Context:** is the scientific context motivating the work correctly presented?
- [x] **Methodology:** is the approach taken in the work justified, presented with enough details and reference to reproduce it?
- [ ] **Results:** are the results presented and compared to approaches with similar goals?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @lucaferranti, @maleadt it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/JuliaCon/proceedings-review) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/JuliaCon/proceedings-review:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
Wordcount for `paper.tex` is 5545

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00128/jcon.00128/10.21105.jcon.00128.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00128/jcon.00128/10.21105.jcon.00128.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.21 s (204.6 files/s, 295535.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SVG                              8              1              1          48211
Julia                           21            414            924           5980
TeX                              8            325            231           2734
TOML                             2            306              1           1418
Ruby                             1              8              4             45
Markdown                         1             13              0             35
YAML                             1              2              0             21
-------------------------------------------------------------------------------
SUM:                            42           1069           1161          58444
-------------------------------------------------------------------------------


Statistical information for the repository '9a72e007480fe464c68fc4a2' was
gathered on 2023/04/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Can Ozmaden                      1            57              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Can Ozmaden                  57          100.0          0.0                7.02
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/141000671 is OK
- 10.1287/opre.38.5.911 is OK
- 10.1109/ISSSTA.1992.665623 is OK
- 10.3390/s121013417 is OK
- 10.1109/TWC.2004.833467 is OK
- 10.1109/TPDS.2018.2872064 is OK
- 10.21105/joss.02673 is OK
- 10.5281/zenodo.5870363 is OK
- 10.1109/ICINIS.2008.99 is OK
- 10.21105/joss.03349 is OK
- 10.5281/zenodo.5933659 is OK
- 10.5281/zenodo.5933726 is OK

MISSING DOIs

- 10.1007/s10291-016-0516-2 may be a valid DOI for title: Correlation acceleration in GNSS software receivers using a CUDA-enabled GPU
- 10.1109/plans.1996.509077 may be a valid DOI for title: Adaptive antenna arrays for interference cancellation in GPS and GLONASS receivers
- 10.33012/2018.15873 may be a valid DOI for title: Estimation of antenna array manifolds based on sparse measurements
- 10.1186/s13638-018-1132-3 may be a valid DOI for title: Research on multi-constellation GNSS compatible acquisition strategy based on GPU high-performance operation
- 10.22457/jmi.v20a05192 may be a valid DOI for title: Satellite Navigation Simulation Signal Generation Method Based on GPU Acceleration
- 10.1109/globalsip.2015.7418431 may be a valid DOI for title: An accelerated signal tracking module using a heterogeneous multi-GPU platform for real-time GNSS software receiver
- 10.4018/ijghpc.2014070102 may be a valid DOI for title: Accelerating a cloud-based software GNSS receiver

INVALID DOIs

- https://doi.org/10.1002/navi.29 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
:wave: @maleadt, please update us on how your review is going (this is an automated reminder).

**Comment by whedon** [comment]
:wave: @lucaferranti, please update us on how your review is going (this is an automated reminder).

**Comment by whedon** [comment]
:wave: @maleadt, please update us on how your review is going (this is an automated reminder).

**Comment by whedon** [comment]
:wave: @lucaferranti, please update us on how your review is going (this is an automated reminder).

**Comment by lucaferranti** [comment]
apologies for the radio silence, I"ll try to get the review done this week!

**Comment by lucaferranti** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00128/jcon.00128/10.21105.jcon.00128.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00128/jcon.00128/10.21105.jcon.00128.pdf) :page_facing_up: :point_left:

**Comment by lucaferranti** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/141000671 is OK
- 10.1287/opre.38.5.911 is OK
- 10.1109/ISSSTA.1992.665623 is OK
- 10.3390/s121013417 is OK
- 10.1109/TWC.2004.833467 is OK
- 10.1109/TPDS.2018.2872064 is OK
- 10.21105/joss.02673 is OK
- 10.5281/zenodo.5870363 is OK
- 10.1109/ICINIS.2008.99 is OK
- 10.21105/joss.03349 is OK
- 10.5281/zenodo.5933659 is OK
- 10.5281/zenodo.5933726 is OK

MISSING DOIs

- 10.1007/s10291-016-0516-2 may be a valid DOI for title: Correlation acceleration in GNSS software receivers using a CUDA-enabled GPU
- 10.1109/plans.1996.509077 may be a valid DOI for title: Adaptive antenna arrays for interference cancellation in GPS and GLONASS receivers
- 10.33012/2018.15873 may be a valid DOI for title: Estimation of antenna array manifolds based on sparse measurements
- 10.1186/s13638-018-1132-3 may be a valid DOI for title: Research on multi-constellation GNSS compatible acquisition strategy based on GPU high-performance operation
- 10.22457/jmi.v20a05192 may be a valid DOI for title: Satellite Navigation Simulation Signal Generation Method Based on GPU Acceleration
- 10.1109/globalsip.2015.7418431 may be a valid DOI for title: An accelerated signal tracking module using a heterogeneous multi-GPU platform for real-time GNSS software receiver
- 10.4018/ijghpc.2014070102 may be a valid DOI for title: Accelerating a cloud-based software GNSS receiver

INVALID DOIs

- https://doi.org/10.1002/navi.29 is INVALID because of 'https://doi.org/' prefix
```

**Comment by matbesancon** [comment]
@whedon assign @lucaferranti as editor

**Comment by lucaferranti** [comment]
@whedon show commands

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by lucaferranti** [comment]
@whedon set 0.1 as version

**Comment by whedon** [comment]
I'm sorry @lucaferranti, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by matbesancon** [comment]
@whedon assign @luraess as editor

**Comment by matbesancon** [comment]
@whedon assign @fcdimitr as editor

**Comment by ranjanan** [comment]
@whedon assign @lucaferranti as editor

**Comment by ranjanan** [comment]
@carstenbauer do you have the power to assign editors?

**Comment by lucaferranti** [comment]
@whedon set 0.1 as version

**Comment by whedon** [comment]
I'm sorry @lucaferranti, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by lucaferranti** [comment]
maybe editors need to be members of the juliacon organization?

**Comment by matbesancon** [comment]
@whedon set @fcdimitr as reviewer

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by matbesancon** [comment]
@whedon assign @fcdimitr as editor

**Comment by fcdimitr** [comment]
:wave: @coezmaden: I see that @maleadt has posted his review in a separate issue (https://github.com/coezmaden/GPUAcceleratedTracking/issues/5). Could you update us on your efforts to address the comments and revise the manuscript?

:wave: @lucaferranti: Could you give us an update on how your review is going?

Thank you!

**Comment by fcdimitr** [comment]
👋 @coezmaden: Could you please update us on the progress of addressing the reviewer's comments? I enabled the flag `author-action-required` until we hear back from you. If we do not receive a response within 25 days, the issue will be closed, and you will have to start a new submission from scratch. Thank you!

**Comment by coezmaden** [comment]
> 👋 @coezmaden: Could you please update us on the progress of addressing the reviewer's comments? I enabled the flag `author-action-required` until we hear back from you. If we do not receive a response within 25 days, the issue will be closed, and you will have to start a new submission from scratch. Thank you!

Sorry for the late reply and inactivity. The original hardware and the funding for the project behind this submission has been finalized after the review came. I am afraid I cannot provide any viable update to the paper due to time and the lack of original hardware reasons. Apologies for the caused inconvenience, but I must retract this submission.

**Comment by fcdimitr** [comment]
Thank you for the update; I am closing this issue.

**Comment by lucaferranti** [comment]
@editorialbot reject
